source 'https://rubygems.org'

gem 'data_mapper', '1.2.0'
gem 'dm-migrations', '1.2.0'
gem 'dm-sqlite-adapter', '1.2.0'
gem 'json', '~>1.6'
gem 'shotgun', '0.9.2'
# gem 'sinatra','1.4.8'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'slim', '3.0.8'
gem 'thin', '1.7.0'